global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'payment-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-api:8080']

  - job_name: 'pg-mock'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pg-mock:8081']

  - job_name: 'worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker:8082']