spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: payment-api
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      maximum-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  pg:
    url: http://localhost:8081
  worker:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: payment-api
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: payment-api
  datasource:
    url: jdbc:mysql://mysql:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      maximum-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
server:
  pg:
    url: http://pg-mock:8081
  worker:
    url: http://worker:8082